
pipeline {
    agent {
        docker {
            image 'node:lts-bullseye-slim'
            args '-p 3333:3333'
        }
    }
    stages {
       stage('Build') {
            steps {
                
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'sudo chmod -R 777 ./jenkins/scripts/test.sh'
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') { 
            steps {
                sh 'sudo chmod -R 777 ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh' 
                input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                sh 'sudo chmod -R 777 ./jenkins/scripts/kill.sh'
                sh './jenkins/scripts/kill.sh' 
            }
        }
    }
}