
pipeline {
    agent {
        docker {
            image 'node:lts-bullseye-slim'
            args '-p 3333:3333'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
    }
}